src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $tel_number = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez renseigner le nom")]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $society = null;

    #[ORM\Column]
    private ?bool $contacted = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTelNumber(): ?string
    {
        return $this->tel_number;
    }

    public function setTelNumber(?string $tel_number): static
    {
        $this->tel_number = $tel_number;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getSociety(): ?string
    {
        return $this->society;
    }

    public function setSociety(?string $society): static
    {
        $this->society = $society;

        return $this;
    }

    public function isContacted(): ?bool
    {
        return $this->contacted;
    }

    public function setContacted(bool $contacted): static
    {
        $this->contacted = $contacted;

        return $this;
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\ContactRepository;
use Doctrine\ORM\EntityManagerInterface;
use App\Entity\Contact;
use App\Form\ContactFormType;

class ContactController extends AbstractController
{
    #[Route('/contacts', name: 'app_contacts')]
    public function index(ContactRepository $repo): Response
    {
        $contacts = $repo->findAll();
        
        return $this->render('contact/index.html.twig', [
            'contacts' => $contacts,
        ]);
    }

    #[Route('/contact/add', name: 'add_contact')]
    public function add(Request $req, EntityManagerInterface $em): Response
    {
        $contact = new Contact();

        $form = $this->createForm(ContactFormType::class, $contact);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid())
        {
            $em->persist($contact);
            $em->flush();

            $this->addFlash("success", "Contact ajouté");

            return $this->redirectToRoute("app_contacts");
        }

        return $this->render('contact/add.html.twig', [
            'myForm' => $form,
        ]);
    }

    #[Route("/contact/view/{id}", name: "view_contact")]
    public function view(int $id, ContactRepository $repo): Response
    {
        $contact = $repo->find($id);

        return $this->render("contact/view.html.twig", ["contact" => $contact]);
    }

    #[Route('/contact/edit/{id}', name: 'edit_contact')]
    public function edit(int $id, Request $req, ContactRepository $repo, EntityManagerInterface $em): Response
    {
        $contact = $repo->find($id);

        $form = $this->createForm(ContactFormType::class, $contact);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid())
        {
            $em->flush();

            $this->addFlash("success", "Contact mis à jour");

            return $this->redirectToRoute("app_contacts");
        }

        return $this->render('contact/edit.html.twig', [
            'myForm' => $form,
        ]);
    }

    #[Route('/contact/delete/{id}', name: 'delete_contact')]
    public function delete(int $id, ContactRepository $repo, EntityManagerInterface $em): Response
    {
        $contact = $repo->find($id);

        $em->remove($contact);
        $em->flush();

        $this->addFlash("success", "Le contact a bien été supprimé");
        return $this->redirectToRoute("app_contacts");
    }
}

templates/contact/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'un contact{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Ajout d'un contact</h1>

    {{ form_start(myForm) }}

    <div class="d-flex flex-column">
        {{ form_row(myForm.tel_number) }}
        {{ form_row(myForm.name) }}
        {{ form_row(myForm.email) }}
        {{ form_row(myForm.society) }}
        {{ form_row(myForm.contacted) }}
    </div>

    {{ form_end(myForm) }}

</div>

{% endblock %}

templates/contact/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Mise à jour contact{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Mise à jour d'un contact</h1>

    {{ form_start(myForm) }}

    <div class="d-flex flex-column">
        {{ form_row(myForm.tel_number) }}
        {{ form_row(myForm.name) }}
        {{ form_row(myForm.email) }}
        {{ form_row(myForm.society) }}
        {{ form_row(myForm.contacted) }}
    </div>

    {{ form_end(myForm) }}

</div>

{% endblock %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de vos contacts{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Liste de vos contacts</h1>

    <br>

    <a type="button" class="btn btn-info" href="{{ path('add_contact') }}">Ajouter un contact</a>
    <div type="button" class="btn btn-danger" id="deleteSelected">Supprimer</div>
    <br>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="month" id="month" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                    <button type="button" class="btn btn-primary" id="validMonth">Valider</button>
                </div>
            </div>
        </div>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Nom</th>
                <th scope="col">Société</th>
                <th scope="col">Adresse email</th>
                <th scope="col">Numéro de tél</th>
                <th scope="col">Contacté ?</th>
            </tr>
        </thead>
        <tbody>
            {% for contact in contacts %}
                <tr>
                    <th scope="row">{{ contact.name }}</th>
                    <td>{{ contact.society is not null ? contact.society : "N/A" }}</td>
                    <td>{{ contact.email is not null ? contact.email : "N/A" }}</td>
                    <td>{{ contact.telNumber is not null ? contact.telNumber : "N/A" }}</td>
                    <td>{{ contact.contacted ? "Oui" : "Non" }}</td>
                    <td><a type="button" class="btn btn-info" href={{ path('view_contact', {'id': contact.id}) }}>Détails</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

templates/contact/view.html.twig
{% extends "base.html.twig" %}

{% block title %}Détail du contact{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Détail du contact</h1>

    <table class="table table-hover mb-5">
        <tbody>
            <tr><th scope="col">Nom</th> <td>{{ contact.name }}</td></tr>
            <tr><th scope="col">Société</th> <td>{{ contact.society is not null ? contact.society : "N/A" }}</td></tr>
            <tr><th scope="col">Adresse email</th> <td>{{ contact.email is not null ? contact.email : "N/A" }}</td></tr>
            <tr><th scope="col">Numéro de tél</th> <td>{{ contact.telNumber is not null ? contact.telNumber : "N/A" }}</td></tr>
            <tr><th scope="col">Contacté ?</th> <td>{{ contact.contacted ? "Oui" : "Non" }}</td></tr>
        </tbody>
    </table>

    <div class="d-flex flex-inline">
        <a type="button" class="btn btn-success mx-2" href="{{ path('app_contacts') }}">Listes de vos contacts</a>
        <a type="button" class="btn btn-warning mx-2" href="{{ path('edit_contact', {'id': contact.id}) }}">Modifier ce contact</a>

        <form action="{{ path('delete_contact', {id: contact.id}) }}" method="post">
            <input type="hidden" name="_method" value="DELETE">
            <button type="submit" class="btn btn-danger mx-2">Supprimer ce contact</button>
        </form>
    </div>

</div>

{% endblock %}