src/Entity/PartialCand.php
<?php

namespace App\Entity;

use App\Repository\PartialCandRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PartialCandRepository::class)]
class PartialCand
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $society = null;
    
    #[ORM\Column(length: 255)]
    private ?string $contract_searched = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comments = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $candidacy_date = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $relaunch_date = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $issue = null;

    #[ORM\Column(length: 255)]
    private ?string $job = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSociety(): ?string
    {
        return $this->society;
    }

    public function getContractSearched(): ?string
    {
        return $this->contract_searched;
    }

    public function setSociety(string $society): static
    {
        $this->society = $society;

        return $this;
    }

    public function setContractSearched(string $contract_searched): static
    {
        $this->contract_searched = $contract_searched;

        return $this;
    }

    public function getComments(): ?string
    {
        return $this->comments;
    }

    public function setComments(?string $comments): static
    {
        $this->comments = $comments;

        return $this;
    }

    public function getCandidacyDate(): ?\DateTimeInterface
    {
        return $this->candidacy_date;
    }

    public function setCandidacyDate(\DateTimeInterface $candidacy_date): static
    {
        $this->candidacy_date = $candidacy_date;

        return $this;
    }

    public function getRelaunchDate(): ?\DateTimeInterface
    {
        return $this->relaunch_date;
    }

    public function setRelaunchDate(?\DateTimeInterface $relaunch_date): static
    {
        $this->relaunch_date = $relaunch_date;

        return $this;
    }

    public function getIssue(): ?string
    {
        return $this->issue;
    }

    public function setIssue(?string $issue): static
    {
        $this->issue = $issue;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(string $job): static
    {
        $this->job = $job;

        return $this;
    }
}

src/Controller/PartialCandController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\PartialCandRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\PartialCand;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class PartialCandController extends AbstractController
{
    #[Route('/partial_cand', name: 'app_partial_cand')]
    public function index(PartialCandRepository $repo): Response
    {
        $queryBuilder = $repo->createQueryBuilder("c");

        $queryBuilder->orderBy("c.candidacy_date", "DESC");
        
        $candidacies = $queryBuilder->getQuery()->getResult();

        $this->getNeedRelaunch($candidacies);
        
        return $this->render('partial_cand/index.html.twig',
        [
            'candidacies' => $candidacies,
        ]);
    }

    #[Route('/partial_cand/add', name: 'add_part_cand')]
    public function add(Request $request, EntityManagerInterface $entityManager): Response
    {
        $candidacy = new PartialCand();
        
        $form = $this->createFormBuilder($candidacy)

        ->add("society", TextType::class,
        [
            "attr" =>
            [
                "class" => "form-control"
            ],
            "label" => "Nom de la société"
        ])

        ->add("contractSearched", ChoiceType::class,
        [
            "attr" =>
            [
                "class" => "form-select"
            ],
            "choices" =>
            [
                "CDD/CDI" => "CDD/CDI",
                "Stage" => "Stage",
                "Alternance" => "Alternance",
                "Autre" => "Autre"
            ],
            "label" => "Type de contrat recherché"
        ])

        ->add("candidacy_date", DateType::class,
        [
            "widget" => "single_text",
            "label" => "Date de candidature",
            "attr" =>
            [
                "class" => "form-control form-icon-trailing"
            ],
            "data" => new \DateTimeImmutable()
        ])

        ->add("job", TextType::class,
        [
            "attr" =>
            [
                "class" => "form-control"
            ],
            "label" => "Poste proposé / recherché"
        ])

        ->add("comments", TextareaType::class,
        [
            "attr" =>
            [
                "class" => "form-control"
            ],
            "label" => "Commentaires",
            "required" => false
        ])

        ->getForm();
    
        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid())
        {
            $entityManager->persist($candidacy);

            $entityManager->flush();

            return $this->redirectToRoute('app_partial_cand');
        }
        
        return $this->render('partial_cand/add.html.twig', ["form" => $form]);
    }

    #[Route('/partial_cand/view/{id}', name: 'view_partial_cand')]
    public function view($id, PartialCandRepository $repo): Response
    {
        $cand = $repo->find($id);

        $this->getNeedRelaunchOne($cand);

        return $this->render('partial_cand/view.html.twig', ["cand" => $cand]);
    }

    #[Route('/partial_cand/edit/{id}', name: 'edit_partial_cand')]
    public function edit($id, Request $request, PartialCandRepository $repo, EntityManagerInterface $entityManager): Response
    {
        $cand = $repo->find($id);

        $form = $this->createFormBuilder($cand)

            ->add("society", TextType::class,
            [
                "attr" =>
                [
                    "class" => "form-control"
                ],
                "label" => "Nom de la société"
            ])

            ->add("contractSearched", ChoiceType::class,
            [
                "attr" =>
                [
                    "class" => "form-select"
                ],
                "choices" =>
                [
                    "CDD/CDI" => "CDD/CDI",
                    "Stage" => "Stage",
                    "Alternance" => "Alternance",
                    "Autre" => "Autre"
                ],
                "label" => "Type de contrat recherché"
            ])

            ->add("candidacy_date", DateType::class,
            [
                "widget" => "single_text",
                "label" => "Date de candidature",
                "attr" =>
                [
                    "class" => "form-control form-icon-trailing"
                ]
            ])

            ->add("relaunch_date", DateType::class,
            [
                "widget" => "single_text",
                "label" => "Date de relance",
                "attr" =>
                [
                    "class" => "form-control form-icon-trailing"
                ],
                "required" => false
            ])

            ->add("comments", TextareaType::class,
            [
                "attr" =>
                [
                    "class" => "form-control"
                ],
                "label" => "Commentaires",
                "required" => false
            ])

            ->add("issue", ChoiceType::class,
            [
                "attr" =>
                [
                    "class" => "form-select"
                ],
                "choices" =>
                [
                    "Pas de réponse pour le moment" => null,
                    "Entretien obtenu 😀" => "ok",
                    "Réponse négative 😔" => "no"
                ],
                "label" => "Issue de la candidature"
            ])
            
            ->getForm();
			
			$form->handleRequest($request);	
			
			if($form->isSubmitted() && $form->isValid())
			{
				$entityManager->persist($cand);
                $entityManager->flush();

                return $this->redirectToRoute("app_partial_cand");
			}
			
		return $this->render('partial_cand/edit.html.twig', ["form" => $form]);
    }

    #[Route('/partial_cand/delete/{id}', name: 'delete_partial_cand')]
    public function delete($id, PartialCandRepository $repo, EntityManagerInterface $entityManager): Response
    {
        $cand = $repo->find($id);

        $entityManager->remove($cand);
        $entityManager->flush();

        return $this->redirectToRoute("app_partial_cand");
    }

    private function getNeedRelaunch(&$candidacies)
    {
        foreach($candidacies as $cand)
        {
            if($cand->getRelaunchDate() == null && $cand->getIssue() == null)
            {
                $now = new \DateTimeImmutable();

                $delay = $now->diff($cand->getCandidacyDate())->format("%a");

                if($delay < 56)
                {
                    $cand->needRelaunch = "#5bfe6a";
                }

                else
                if($delay >= 56 && $delay < 63)
                {
                    $cand->needRelaunch = "yellow";
                }

                else
                if($delay >= 63 && $delay < 70)
                {
                    $cand->needRelaunch = "#f9a33e";
                }

                else
                if($delay >= 70 && $delay < 77)
                {
                    $cand->needRelaunch = "red";
                }

                else
                if($delay >= 77)
                {
                    $cand->needRelaunch = "black";
                }
            }

            else
            {
                $cand->needRelaunch = "white";
            }
        }
    }

    private function getNeedRelaunchOne(&$cand)
    {
        if($cand->getRelaunchDate() == null && $cand->getIssue() == null)
        {
            $now = new \DateTimeImmutable();

            $delay = $now->diff($cand->getCandidacyDate())->format("%a");

            if($delay < 56)
            {
                $cand->needRelaunch = "#5bfe6a";
            }

            else
            if($delay >= 56 && $delay < 63)
            {
                $cand->needRelaunch = "yellow";
            }

            else
            if($delay >= 63 && $delay < 70)
            {
                $cand->needRelaunch = "#f9a33e";
            }

            else
            if($delay >= 70 && $delay < 77)
            {
                $cand->needRelaunch = "red";
            }

            else
            if($delay >= 77)
            {
                $cand->needRelaunch = "black";
            }
        }

        else
        {
            $cand->needRelaunch = "white";
        }
    }
}

templates/partial_cand/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajout d'une candidature partielle{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Ajout d'une candidature</h1>

    {{ form_start(form) }}
        {{ form_row(form.society) }}
        <br>
        {{ form_row(form.job) }}
        <br>
        {{ form_row(form.contractSearched) }}
        <br>
        {{ form_row(form.candidacy_date) }}
        <br>
        {{ form_row(form.comments) }}
        <br>
        <button type="submit" class="btn btn-primary">Ajouter la candidature partielle</button>
    {{ form_end(form) }}

    <br>
    <a type="button" class="btn btn-info" href="{{ path('app_partial_cand') }}">Vos candidatures partielles</a>

</div>

<script>
    /*$("#other").hide();

    $("#form_type").click(() =>
    {
        if($("#form_type").val() == "Autre")
        {
            $("#other").show();
        }
    });

    console.log($("#form_type").val("aa"));*/
</script>

{% endblock %}

templates/partial_cand/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier la candidature partielle{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Modifier la candidature partielle</h1>

    {{ form_start(form) }}
        {{ form_row(form.society) }}
        <br>
        {{ form_row(form.contractSearched) }}
        <br>
        {{ form_row(form.candidacy_date) }}
        <br>
        {{ form_row(form.relaunch_date) }}
        <br>
        {{ form_row(form.comments) }}
        <br>
        {{ form_row(form.issue) }}
        <br>
        <button type="submit" class="btn btn-primary">Mettre à jour la candidature partielle</button>
    {{ form_end(form) }}

    <br>
    <a type="button" class="btn btn-info" href="{{ path('app_partial_cand') }}">Vos candidatures partielles</a>

</div>
{% endblock %}

templates/partial_cand/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste de vos candidatures{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Liste de vos candidatures partielles</h1>

    <br>

    <a type="button" class="btn btn-info" href="{{ path('add_part_cand') }}">Ajouter une candidature partielle</a>
    <div type="button" class="btn btn-danger" id="deleteSelected">Supprimer</div>
    <br>

    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <input type="month" id="month" />
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fermer</button>
                    <button type="button" class="btn btn-primary" id="validMonth">Valider</button>
                </div>
            </div>
        </div>
    </div>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col"><input type="checkbox" id="select_all" /></th>
                <th scope="col">Nom de la société</th>
                <th scope="col">Contrat recherché</th>
                <th scope="col">Date de candidature</th>
                <th scope="col">Date de relance</th>
                <th scope="col">Poste proposé / recherhé</th>
                <th scope="col">Issue</th>
                <th scope="col">Urgence relance</th>
            </tr>
        </thead>
        <tbody>
            {% for cand in candidacies %}
                <tr>
                    <td ><input type="checkbox" class="checkbox" id="{{ cand.id }}" /></td>
                    <th>{{ cand.society }}</th>
                    <td>{{ cand.contractSearched }}</td>
                    <td>{{ cand.candidacyDate | date("d-m-Y") }}</td>
                    <td>{{ (cand.relaunchDate is not null) ? (cand.relaunchDate | date("d-m-Y")) : "N/A" }}</td>
                    <td>{{ cand.job }}</td>
                    <td>
                        {% if cand.issue is null %}
                            Sans réponse pour le moment
                        {% elseif cand.issue == "ok" %}
                            <b>Entretien obtenu 😀</b>
                        {% elseif cand.issue == "no" %}
                            <b>Refusé 😔</b>
                        {% endif %}
                    </td>
                    <td style="background-color: {{ cand.needRelaunch }}"></td>
                    <td><a type="button" class="btn btn-info" href={{ path('view_partial_cand', {'id': cand.id}) }}>Détail de la candidature</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

</div>
{% endblock %}

templates/partial_cand/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail de la candidature partielle{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Détail de la candidature partielle</h1>
    <br>

    <ul>
        <li>Vous avez postulé chez <u>{{ cand.society }}</u> le {{ cand.candidacyDate | date("d-m-Y") }} {% if cand.job is not null %} pour le poste de <u>{{ cand.job }}</u>{% endif %}</li>
        
        <li>
            {% if cand.relaunchDate is null %}
                Vous n'avez pas relancé pour le moment
            {% else %}
                Vous avez relancé le {{ cand.relaunchDate | date("d-m-Y") }}
            {% endif %}
        </li>

        {% if cand.comments is not null %}
            <li>
                Vous avez noté les infos suivantes :

                <p>
                    {{ cand.comments | nl2br }}
                </p>
            </li>
        {% endif %}

        <li>
            {% if cand.issue is null %}
                Vous êtes sans réponse pour le moment
            {% elseif cand.issue == "ok" %}
                <b>Entretien obtenu, félicitations !!! 😀😀</b>
            {% elseif cand.issue == "no" %}
                <b>Votre candidature a malheureusement été refusée 😔😔</b>
            {% endif %}
        </li>

        {% if cand.needRelaunch != "white" %}
            <li>
                {% if cand.needRelaunch == "#5bfe6a" %}
                    <b>Il n'est pas encore temps de relancer les recruteurs</b>
                {% elseif cand.needRelaunch == "yellow" %}
                    <b>Une relance serait envisageable</b>
                {% elseif cand.needRelaunch == "#f9a33e" %}
                    <b>Il est important de relancer les recruteurs</b>
                {% elseif cand.needRelaunch == "red" %}
                    <b>Il est urgent de relancer les recruteurs !!</b>
                {% elseif cand.needRelaunch == "black" %}
                    <b>A relancer de toute urgence !!!</b>
                {% endif %}
            </li>
        {% endif %}
    </ul>

    <br>
    <a type="button" class="btn btn-success" href="{{ path('app_partial_cand') }}">Listes de vos candidatures partielles</a>
    <a type="button" class="btn btn-warning" href="{{ path('edit_partial_cand', {'id': cand.id}) }}">Modifier cette candidature</a>
    <a type="button" class="btn btn-danger" href="{{ path('delete_partial_cand', {'id': cand.id}) }}">Supprimer cette candidature</a>

</div>

<div class="modal" id="deleteModal">
    <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Suppression de votre candidature vers <u>{{ cand.society }}</u></h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true"></span>
                    </button>
                </div>
            <div class="modal-body">
                <p>Êtes-vous sûr ?</p>
            </div>
            <div class="modal-footer">
                <a type="button" class="btn btn-primary" href="{{ path('delete_candidacies', {'id': cand.id}) }}">Oui</a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Non</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}